import { Calendar, Code2, Goal, Star, User } from "lucide-react"
import type { ProjectCardProps } from "../../type/type"

const projectsList: ProjectCardProps[] = [
    {
    title: "My virtual Pet - Development helper for child",
    icon: User,
    stackInfo: "Frontend Development",
    iconYear: Calendar,
    year: "2025",
    typeOfProject: ["Production Ready"],
    linkGit: "https://github.com/Carmelo85S/game",
    linkLive: "https://carmelo85s.github.io/game/",
    description:
      "My virtual pet is a game inspired by the most famous tamagotchi. The idea behind the game was to create something that can be helpull in the development for a child. In the game the user needs to take care of a pet, feed him and clean. In teh game there are 3 ways to gain points: mini games, take care of the animal, for example cleaning. With the points gained the user can buy food and drinks for the Pet.",
    completion: "100%",
    performance: "Interactive",
    type: "Team project",
    ratingIcon: Star,
    ratingCount: 5,
    achievementIcon: Goal,
    achievementInfo1: "Developed login system with save in local storage",
    achievementInfo2: "State management with useState()",
    achievementInfo3: "Developed login page and main page",
    achievementInfo4: "Developed functionality, points management, items management",
    techIcon: Code2,
    techInfo: "Technologies & Tools",
    techTask1: "React",
    techTask2: "Sass ",
    color: "bg-slate-900",
    hoverColor: "hover:bg-yellow-900",
  },
    {
    title: "Burger lab - Burger restaurant Landing page",
    icon: User,
    stackInfo: "Frontend Development",
    iconYear: Calendar,
    year: "2025",
    typeOfProject: ["Production Ready"],
    linkGit: "https://github.com/Carmelo85S/burger-lab",
    linkLive: "https://carmelo85s.github.io/burger-lab/",
    description:
      "A modern, responsive restaurant website built with React and Tailwind CSS. It features dynamic menu tabs, animated sections, a contact form, and smooth scroll-based interactions. Perfect for burger joints or any restaurant wanting a clean digital presence.",
    completion: "100%",
    performance: "Optimized",
    type: "Personal project",
    ratingIcon: Star,
    ratingCount: 4,
    achievementIcon: Goal,
    achievementInfo1: "Developed responsive landing page",
    achievementInfo2: "Styled with tailwind",
    achievementInfo3: "Developed a interactive menu",
    achievementInfo4: "Total responsive",
    techIcon: Code2,
    techInfo: "Technologies & Tools",
    techTask1: "React",
    techTask2: "Tailwind",
    color: "bg-slate-900",
    hoverColor: "hover:bg-orange-900/90",
  },
  {
    title: "Seedly - E Commerce website",
    icon: User,
    stackInfo: "Full-Stack Development",
    iconYear: Calendar,
    year: "2025",
    typeOfProject: ["Team Project"],
    linkGit: "https://github.com/roztownsend/Seedly",
    linkLive: "https://seedly-tau.vercel.app",
    description:
      "Seedly is a modern web application designed for gardeners, plant enthusiasts, and eco-conscious consumers. It allows users to explore, purchase, and learn about plant seeds in a user-friendly and inspiring environment.",
    completion: "90%",
    performance: "Very good",
    type: "Team project",
    ratingIcon: Star,
    ratingCount: 4,
    achievementIcon: Goal,
    achievementInfo1: "Developed responsive product catalog with filtering",
    achievementInfo2: "Developed Swagger documentation",
    achievementInfo3: "Developed Shipping information form component",
    achievementInfo4: "Developed checkout page and state management using Zustand",
    techIcon: Code2,
    techInfo: "Technologies & Tools",
    techTask1: "React",
    techTask2: "ExpressJS",
    techTask3: "NodeJS",
    techTask4: "Supabase",
    color: "bg-slate-900",
    hoverColor: "hover:bg-slate-700",
  },
  {
    title: "Lounge9 - Hotel bar booking system",
    icon: User,
    stackInfo: "Full-Stack Development",
    iconYear: Calendar,
    year: "2025",
    typeOfProject: ["Production Ready"],
    linkGit: "https://github.com/Carmelo85S/lounge9-cocktail-bar",
    linkLive: "https://lounge9.vercel.app",
    description:
      "A full-stack web application for Hotel and Bars, booking form and reservation management, with business insights.",
    completion: "100%",
    performance: "Very good",
    type: "Personal project",
    ratingIcon: Star,
    ratingCount: 5,
    achievementIcon: Goal,
    achievementInfo1: "Developed responsive landing page",
    achievementInfo2: "Developed functional booking form connected to database",
    achievementInfo3: "Developed private area for admin where is possible to manage resevation",
    achievementInfo4: "Developed server, database, booking endpoints and chart insight",
    techIcon: Code2,
    techInfo: "Technologies & Tools",
    techTask1: "React",
    techTask2: "ExpressJS",
    techTask3: "NodeJS",
    techTask4: "MongoDB",
    color: "bg-slate-900",
    hoverColor: "hover:bg-emerald-700",
  },
]

export default projectsList
